config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items, only: [:show, :index]
  resources :feeds, except: :show
  root to: "items#index"
  patch '/items/:id/interact', to: 'items#interact', as: 'interact' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/feed.rb
class Feed < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :url, :name, presence: true

  scope :search, ->(keyword) {
   where("name LIKE ?", "%#{keyword}%")
  }

  def get_basic_info
    begin
      f = Feedjira::Feed.fetch_and_parse url
      self.name = f.title if name.blank?
      self.favicon ||= Pismo[f.url].favicon
    rescue
      get_host_info
    end
  end

  private
  def get_host_info
    pismo = Pismo[url]
    self.favicon = pismo.favicon
    self.url = pismo.feed || raise(ArgumentError.new 'RSS inválido')
    get_basic_info
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  # GET /feeds
  def index
   if params[:search]
     @search = Feed.search(params[:search])
   else
      @search = Feed
    end
   @feeds = @search.all
  end

  # GET /feeds/1
  def show
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  def create
    @feed = Feed.new(feed_params)
    begin
      @feed.get_basic_info
    rescue ArgumentError => e
      flash[:error] = e.message
      render :new
      return
    end

    if @feed.save
      redirect_to feeds_path, notice: 'Feed was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /feeds/1
  def update
    if @feed.update(feed_params)
      redirect_to feeds_path, notice: 'Feed was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /feeds/1
  def destroy
    @feed.destroy
    redirect_to feeds_url, notice: 'Feed was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.require(:feed).permit(:name, :url, :favicon)
    end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= form_for(@feed, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @feed.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h4>

      <ul>
      <% @feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div-->
  <div class="form-group">
    <%= f.label :url, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :url, class: "form-control", disabled: !@feed.new_record? %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :tag_list, "Tags", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :tag_list, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Register", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <h4 class="modal-title" id="myModalLabel">Editing Feed</h4>
</div>
<div class="modal-body">
  <%= render 'form' %>
</div>

app/views/feeds/index.html.erb
<%= content_for :navbar_filters do %>
  <%= render 'application/search', locals: {path: 'feeds_path'} %>
  <%= render 'application/calendar', locals: {disabled?: true} %>
<% end %>

<div class="page-header">
  <%= link_to new_feed_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Feed
  <% end %>
  <h1>Listing feeds</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Url</th>
            <th>Favicon</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @feeds) do |feed| %>
            <td><%= feed.name %></td>
            <td><%= feed.url %></td>
            <td><%= feed.favicon %></td>
            <td><%= link_to 'Show', feed %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/feeds/new.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <h4 class="modal-title" id="myModalLabel">New Feed</h4>
</div>
<div class="modal-body">
  <%= render 'form' %>
</div>