config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items, only: [:show, :index]
  resources :feeds, except: :show
  root to: "items#index"
  patch '/items/:id/interact', to: 'items#interact', as: 'interact' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :error, :notice

  def get_filter(params)
    filter = 'all'
    params.each do |key, value|
      case key
      when 'favourites', 'bookmarks', 'history'
        filter = key
      when 'tag'
        filter = value unless value.blank?
      end
    end
    filter
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_date_format(date)
    if date
      delay_seconds = Time.now - date
      delay_minutes = delay_seconds/60
      delay_hours = delay_minutes/60
      delay_days = delay_hours/24

      if delay_minutes < 1
        return pluralize("segundo", delay_seconds.round(0))
      elsif delay_hours < 1
        return pluralize("minuto", delay_minutes.round(0))
      elsif delay_days < 1
        return pluralize("hora", delay_hours.round(0))
      elsif delay_days < 7
        return pluralize("dia", delay_days.round(0))
      else
        date.strftime("%d/%m/%y")
      end
    end
  end

  def human_readable_number(n)
    n > 1000 ? "#{(n.to_f/1000).round(1)} K" : n
  end

  def pluralize(string, number)
    number == 1 ? "1 #{string}" : "#{number} #{string}s"
  end

  def interaction_filters
    [:bookmarks, :favourites, :history]
  end

  def exclusive_filters
    interaction_filters + [:tag, :feed]
  end

  def cumulative_filters
    [:search, :calendar]
  end

  def filters
    exclusive_filters + cumulative_filters
  end

  def safe_params(params)
    # para cada filtro pego o parametro correspondente
    hash = Hash[filters.collect{ |f| [f, params[f]]}]
    # removo aqueles cujo parametro é nulo
    hash.reject{|k,v| v.blank? }
  end

  def link_to_interaction_filter(params, interaction_type, &block)
    filter = interaction_type.to_s
    new_param = {interaction_type => true}
    link_to_filter('items_path', params, filter, new_param, interaction_type, &block)
  end

  def link_to_tag_filter(path, params, tag, &block)
    filter = tag
    new_param = {tag: tag}
    link_to_filter(path, params, filter, new_param, &block)
  end

  def link_to_filter(path, params, filter, new_param = nil, id = nil)
    # acrecento um novo parâmetro referente ao filtro exclusivo se existir
    hash = new_param || Hash.new
    # incluo os parametros dos filtros cumulativos que existirem
    cumulative_filters.each do |f|
      hash[f] = params[f] unless params[f].blank?
    end

    active = 'active' if filter == @filter
    css = { class: "list-group-item #{active}" }
    css.merge!(id: id) if id

    link_to send(path, hash), css do
      yield
    end
  end

  def link_to_clear_filter(path, type, params)
    hash = safe_params(params).except(type)

    link_to send(path, hash), class: "btn btn-default #{"disabled" unless params[type]}" do
      yield
    end
  end

  def active_icon?(user, item, type)
    inter = Interaction.find_by(user: user, item: item)
    active = 'active' if inter && inter.send(type.to_s + '?')
  end

  def interaction_icon(type, icon, user, item)
    # pega a interação ligando o usuario ao item
    inter = Interaction.find_by(user: user, item: item)
    # verifica se é ativa
    active = 'active' if inter && inter.send(type.to_s + '?')
    # link para toggle da interação com um ícone
    hash = safe_params(params)
    hash[type] = :toggle
    link_to interact_path(item, hash), method: :patch, class: 'interaction' do
      content_tag :span, "", class: "glyphicon glyphicon-#{icon} #{active}"
    end
  end
end

app/views/application/_calendar.html.erb
<%= form_tag items_path, method: 'get', id: "calendar", class: "navbar-form navbar-left", role: "calendar" do %>
  <div class="form-group">
    <% [:serch, :feed].each do |f| %>
      <%= hidden_field_tag f, params[f] if params[f] %>
    <% end %>
    <%= text_field_tag :calendar, params[:calendar], class: "form-control", id: "calendar-picker", disabled: locals[:disabled?] %>
  </div>
  <span>
    <button class="btn btn-default <%= "disabled" if locals[:disabled?]%>" type="submit">
      <span class="glyphicon glyphicon-calendar"></span>
    </button>
  </span>
<% end %>

app/views/application/_interaction_filters.html.erb
<div class="list-group" id="interactions" >
  <%= link_to_interaction_filter params, :favourites do %>
    <span class="glyphicon glyphicon-star"></span>
    Favourites
    <span class="badge" id="favourites_count">
      <%= human_readable_number @search.favourites(current_user).count %>
    </span>
  <% end %>
  <!-- a href="#" class="list-group-item">
    <span class="glyphicon glyphicon-retweet"></span>
    Shared
    <span class="badge">17</span>
  </a -->
  <%= link_to_interaction_filter params, :bookmarks do %>
    <span class="glyphicon glyphicon-bookmark"></span>
    Read Later
    <span class="badge" id="bookmarks_count">
        <%= human_readable_number @search.bookmarks(current_user).count %>
    </span>
  <% end %>
  <%= link_to_interaction_filter params, :history do %>
    <span class="glyphicon glyphicon-repeat"></span>
    History
    <span class="badge">
      <%= human_readable_number @search.history(current_user).count %>
    </span>
  <% end %>
</div>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"  aria-controls="navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Esfera Pública", items_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="navbar">
      <%= yield :navbar_filters %>
    </div> <!-- navbar-collapse -->
  </div>
</nav>

app/views/application/_search.html.erb
<%= form_tag send(locals[:path]), method: 'get', id: "search", class: "navbar-form navbar-left", role: "search" do %>
  <div class="form-group">
    <% [:calendar, :feed].each do |f| %>
      <%= hidden_field_tag f, params[f] if params[f] %>
    <% end %>
    <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Procurar" %>
  </div>
  <span>
    <button class="btn btn-default" type="submit">
      <span class="glyphicon glyphicon-search"></span>
    </button>
  </span>
<% end %>

app/views/application/_tag_filters.html.erb
<div class="list-group" >
  <%= link_to new_feed_path, data: {behavior: "modal"}, class: "list-group-item list-group-item-info" do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Feed
  <% end %>
  <%= link_to_filter locals[:path], params, 'all' do %>
    <span class="badge">
      <%= human_readable_number @search.count %>
    </span>
    all
  <% end %>
  <% current_user.owned_tags.each do |tag| %>
    <%= link_to_tag_filter locals[:path], params, tag.name do %>
      <span class="badge">
        <%= human_readable_number @search.tagged_with(tag.name).count %>
      </span>
      <%= tag.name %>
    <% end %>
  <% end %>
</div>

app/views/application/_user_menu.html.erb
<ul class="nav navbar-nav navbar-left">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
      <span class="glyphicon glyphicon-user"></span>
      <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li>
        <%= link_to items_path do %>
        <span class="glyphicon glyphicon-home"></span>
        Itens
        <% end %>
      </li>
      <li>
        <%= link_to feeds_path do %>
        <span class="glyphicon glyphicon-cog"></span>
        Feeds
        <% end %>
      </li>
      <li role="separator" class="divider"></li>
      <li>
        <%= link_to 'Account', edit_user_registration_path %>
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
      </li>
    </ul>
  </li>
</ul>